### ISSUE TITLE
entrance.service should be installed to /usr/lib/systemd/system/

### ISSUE THREAD

**Issue by SolarAquarion** [Obsidian-StudiosInc/entrance#11]
Because the symlinks are in /etc/systemd/system

**Comment by wltjr** [comment]
That figures! :) I should have gone with your /usr/lib :P What distro? Seems odd, per man page seems they should have different contents. No worries, I should have just stuck to suggested...

**Comment by wltjr** [comment]
Lets try that again. Just fixed, Thanks for testing and reporting symlinks... :)

**Comment by SolarAquarion** [comment]
Arch

**Comment by wltjr** [comment]
Interesting, wonder why they do that.
