### ISSUE TITLE
Build Failure via meson_options

### ISSUE THREAD

**Issue by SolarAquarion** [Obsidian-StudiosInc/entrance#31]
meson_options.txt:9:0: ERROR:  Option name debug is reserved.

**Comment by wltjr** [comment]
That seems new, what version of meson? I guess it does not dislike the usage in the main file. I guess I need to omit the debug option from that file. Part of mesons growing pains. They tend to make changes that are not legacy complaint, so breaks stuff. I assume your running a newer version I haven't built entrance under. Thus the error. Thanks for the report!

**Comment by SolarAquarion** [comment]
I got the error from the aur, they also were posting that problem to other
forums

**Comment by wltjr** [comment]
I am tempted to replace meson with cmake. I do not like versions changing such that they break existing builds. Meson still seems to new... In Travis I am using 0.44, I just installed 0.48.1 replacing 0.47.1. I do not want to keep fixing or dealing with the build system. At least when I am not adding new features and nothing has changed.

**Comment by wltjr** [comment]
Looking back at the history, this is the 3rd time meson changes broke entrance build. I think I am done with meson. I am going to work on cmake build system and drop meson till the project matures. I do not want to have to worry about versions, installing newer python in travis and a whole slew of other stuff to use meson. Just not worth the time... Lost to much time on meson as is....

**Comment by SolarAquarion** [comment]
Modern cmake is a lot cleaner as far as I know.

**Comment by wltjr** [comment]
A temporary solution is to just comment out those lines in meson_options.txt. I doubt most need to build it with debug enabled. That is mostly for development and CI stuff like code coverage etc.

**Comment by wltjr** [comment]
@SolarAquarion do you need a new tag for the AUR package? Or is this being pulled live from git?

**Comment by SolarAquarion** [comment]
Live from git

**Comment by wltjr** [comment]
Ok cool, if you need a new tag just let me know. I plan to do a new release. Though was hoping to resolve the #30 before next tag/release. But I can due to the issues with meson if needed. Getting no love from upstream as usual on #30. Pretty odd as it broke between beta and release. Not to many commits, just haven't been able to nail it down.
