### ISSUE TITLE
Enlightenment does not start

### ISSUE THREAD

**Issue by RossComputerGuy** [Obsidian-StudiosInc/entrance#38]
## Description
Logging in doesn't start Enlightenment

![shot-2020-01-05_21-15-03](https://user-images.githubusercontent.com/19699320/71796765-2b21f380-3000-11ea-8269-437f8bbd7beb.jpg)

## Steps to reproduce
1. Run ExpidusOS
2. Start entrance from systemd
3. Log in as a user
...

## How entrance is started
systemd service

## System information
- ExpidusOS (https://github.com/ExpidusOS)
- Pam enabled
- Consolekit disabled
- Systemd
- EFL Version 1.22.3
- Entrance v3.0.0_alpha6

**Comment by wltjr** [comment]
That is pretty interesting. I do not believe entrance has been tested or ran under systemd, I could be wrong there. Were you using auto-login, or manually logged in via the entrance UI? Can you provide the entrance.log file? You might want to try it without the --nodaemon option.

**Comment by RossComputerGuy** [comment]
Manual log in, when I get home I'll dump the log file.

**Comment by wltjr** [comment]
Ok, thank you very much! Hopefully, the log file will show if a session was started, attempted to be started, or if something went wrong. I assume, you got a visual greeter/UI and were able to enter your log in information. What happened after that, anything? Thanks again for the report!

**Comment by RossComputerGuy** [comment]
After clicking log in, the screen went black then showed the the log in screen.

**Comment by wltjr** [comment]
That is normal for when you log out. Since its failing to launch E or a session, it is just returning to the log in screen. Hopefully, the log shows something meaningful as to what went wrong.

**Comment by RossComputerGuy** [comment]
I've attached the [log file](https://github.com/Obsidian-StudiosInc/entrance/files/4028327/entrance.log)

**Comment by wltjr** [comment]
Thank you for the log file! I see a few issues.

- This has something to do with entrance log domain. Not major, just something I have not seen before.
[../src/daemon/entrance.c:161](https://github.com/Obsidian-StudiosInc/entrance/blob/master/src/daemon/entrance.c#L161) _entrance_client_error() Failed to connect to bus: No such file or directory

- You might need to edit the path to sessreg in entrance.conf per this error
sh: /usr/bin/sessreg: No such file or directory

- I think this one is related to sessreg.
/usr/bin/xauth:  file /root/.Xauthority does not exist

- It looks like your logging in as root vs another user per these lines, plus the previous Xauthority file location
```
../src/daemon/entrance_history.c:146 entrance_history_push() History create a new entry for root
../src/daemon/entrance_session.c:392 entrance_session_login() launching session /usr/bin/enlightenment_start for user root
```

- Finally, this is of concern. In the initial issue report said Consolekit was disabled. Either there is a problem with meson not setting ```HAVE_CONSOLEKIT``` or something. With that disabled it should be starting the session differently, per [these lines](https://github.com/Obsidian-StudiosInc/entrance/blob/master/src/daemon/entrance_session.c#L192). You can see it calling ck-launch-session to start a session for root in this line
```
../src/daemon/entrance_session.c:199 _entrance_session_run() Executing: /bin/bash --login -c ck-launch-session /etc/entrance/Xsession  /usr/bin/enlightenment_start > /root/.entrance_session.log 2>&1
```

I think the biggest issue is with sessreg not being found. Hopefully, you have that program in some other location. The other potential show stopper is the ck-launch-session command. If you do not have consolekit, then that is sure to fail as well. Those two things should be why it is failing to launch a session. Let's see about resolving those issues and go from there.

**Comment by RossComputerGuy** [comment]
I pushed a commit (mentioned it in the title), that should fix Entrance. I'll have a look once it compiles.

**Comment by RossComputerGuy** [comment]
![shot-2020-01-06_20-37-16](https://user-images.githubusercontent.com/19699320/71868670-fe371480-30c3-11ea-931f-24ec54d1ade1.jpg)
[entrance.log](https://github.com/Obsidian-StudiosInc/entrance/files/4028896/entrance.log)
I got a different error now @wltjr, I added pulseaudio and that fixed the dbus issue.

**Comment by RossComputerGuy** [comment]
It looks like its still the ConsoleKit issue even though I disabled ConsoleKit.

**Comment by RossComputerGuy** [comment]
I forgot to clean the directory source so Buildroot would rebuild Entrance, did that now and it works!

**Comment by wltjr** [comment]
Glad you got it all squared away. Eventually, dbus will be a direct dependency as part of logind/elogind integration. I plan to use dbus to interact with logind/elogind, rather than via a shell. Not sure why pulseaudio was needed. That maybe more related to how EFL was built than entrance itself, as entrance has no audio, or even a reliance on dbus at this time.

**Comment by RossComputerGuy** [comment]
Dbus was saying the pulse user couldn't be found so it was stopping
