### ISSUE TITLE
UI problems

### ISSUE THREAD

**Issue by SolarAquarion** [Obsidian-StudiosInc/entrance#46]
The user switcher is a bit small.

**Comment by wltjr** [comment]
Do you mean the icons are small and/or missing? I am unclear what you are referencing.

**Comment by SolarAquarion** [comment]
![20200426_165257](https://user-images.githubusercontent.com/5307016/80319534-b822cf80-87de-11ea-9022-d4173d34d456.jpg)
![20200426_165251](https://user-images.githubusercontent.com/5307016/80319538-beb14700-87de-11ea-882a-10087c0935ac.jpg)

**Comment by SolarAquarion** [comment]
Also the session switcher should be sorted by name perhaps

**Comment by SolarAquarion** [comment]
Oh, i sent you a DM via IRC

**Comment by wltjr** [comment]
Thanks for the screenshots, I have not seen that before. I was thinking about changing that up and dropping the images and removing the username field, or hiding it at least. I guess now is a good time given the issue. Thanks for the report!

Yes, the sessions should be sorted by name. I will look into addressing that as well.

**Comment by wltjr** [comment]
That should resolve the issue. Although, there could still be another with excess users. Eventually, I will change the UI a bit to look more like [enter](https://github.com/wfx/enter/blob/master/data/shot.jpg) or their [mockup](https://github.com/wfx/enter/blob/master/data/mock_info.png). Or at least, have some alternative themes for entrance, as the UI is done outside the code via edje and edc files.
