### ISSUE TITLE
build failure with meson

### ISSUE THREAD

**Issue by SolarAquarion** [Obsidian-StudiosInc/entrance#7]
FAILED: src/bin/entrance_client@exe/entrance_conf_user.c.o 
ccache cc  -Isrc/bin/entrance_client@exe -Isrc/bin -I../entrance/src/bin -I/usr/include/elementary-1 -I/usr/include/libdrm -I/usr/include/ecore-wl2-1 -I/usr/include/ecore-fb-1 -I/usr/include/ecore-x-1 -I/usr/include/elocation-1 -I/usr/include/emotion-1 -I/usr/include/ethumb-client-1 -I/usr/include/ethumb-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/eio-1 -I/usr/include/efreet-1 -I/usr/include/ecore-ipc-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-drm2-1 -I/usr/include/elput-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/evas-1 -I/usr/include/evas-1/canvas -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/luajit-2.1 -I/usr/include/eet-1 -I/usr/include/emile-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -include config.h -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -pthread -MMD -MQ 'src/bin/entrance_client@exe/entrance_conf_user.c.o' -MF 'src/bin/entrance_client@exe/entrance_conf_user.c.o.d' -o 'src/bin/entrance_client@exe/entrance_conf_user.c.o' -c ../entrance/src/bin/entrance_conf_user.c
In file included from ../entrance/src/bin/entrance_conf_user.c:1:0:
../entrance/src/bin/entrance_client.h:5:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.
[2/26] Compiling C object 'src/bin/entrance_client@exe/entrance_conf_main.c.o'.
FAILED: src/bin/entrance_client@exe/entrance_conf_main.c.o 
ccache cc  -Isrc/bin/entrance_client@exe -Isrc/bin -I../entrance/src/bin -I/usr/include/elementary-1 -I/usr/include/libdrm -I/usr/include/ecore-wl2-1 -I/usr/include/ecore-fb-1 -I/usr/include/ecore-x-1 -I/usr/include/elocation-1 -I/usr/include/emotion-1 -I/usr/include/ethumb-client-1 -I/usr/include/ethumb-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/eio-1 -I/usr/include/efreet-1 -I/usr/include/ecore-ipc-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-drm2-1 -I/usr/include/elput-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/evas-1 -I/usr/include/evas-1/canvas -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/luajit-2.1 -I/usr/include/eet-1 -I/usr/include/emile-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -include config.h -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -pthread -MMD -MQ 'src/bin/entrance_client@exe/entrance_conf_main.c.o' -MF 'src/bin/entrance_client@exe/entrance_conf_main.c.o.d' -o 'src/bin/entrance_client@exe/entrance_conf_main.c.o' -c ../entrance/src/bin/entrance_conf_main.c
In file included from ../entrance/src/bin/entrance_conf_main.c:1:0:
../entrance/src/bin/entrance_client.h:5:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.
[3/26] Compiling C object 'src/bin/entrance_client@exe/entrance_fill.c.o'.
FAILED: src/bin/entrance_client@exe/entrance_fill.c.o 
ccache cc  -Isrc/bin/entrance_client@exe -Isrc/bin -I../entrance/src/bin -I/usr/include/elementary-1 -I/usr/include/libdrm -I/usr/include/ecore-wl2-1 -I/usr/include/ecore-fb-1 -I/usr/include/ecore-x-1 -I/usr/include/elocation-1 -I/usr/include/emotion-1 -I/usr/include/ethumb-client-1 -I/usr/include/ethumb-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/eio-1 -I/usr/include/efreet-1 -I/usr/include/ecore-ipc-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-drm2-1 -I/usr/include/elput-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/evas-1 -I/usr/include/evas-1/canvas -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/luajit-2.1 -I/usr/include/eet-1 -I/usr/include/emile-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -include config.h -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -pthread -MMD -MQ 'src/bin/entrance_client@exe/entrance_fill.c.o' -MF 'src/bin/entrance_client@exe/entrance_fill.c.o.d' -o 'src/bin/entrance_client@exe/entrance_fill.c.o' -c ../entrance/src/bin/entrance_fill.c
In file included from ../entrance/src/bin/entrance_fill.c:1:0:
../entrance/src/bin/entrance_client.h:5:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.
[4/26] Compiling C object 'src/bin/entrance_client@exe/entrance_conf.c.o'.
FAILED: src/bin/entrance_client@exe/entrance_conf.c.o 
ccache cc  -Isrc/bin/entrance_client@exe -Isrc/bin -I../entrance/src/bin -I/usr/include/elementary-1 -I/usr/include/libdrm -I/usr/include/ecore-wl2-1 -I/usr/include/ecore-fb-1 -I/usr/include/ecore-x-1 -I/usr/include/elocation-1 -I/usr/include/emotion-1 -I/usr/include/ethumb-client-1 -I/usr/include/ethumb-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/eio-1 -I/usr/include/efreet-1 -I/usr/include/ecore-ipc-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-drm2-1 -I/usr/include/elput-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/evas-1 -I/usr/include/evas-1/canvas -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/luajit-2.1 -I/usr/include/eet-1 -I/usr/include/emile-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -include config.h -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -pthread -MMD -MQ 'src/bin/entrance_client@exe/entrance_conf.c.o' -MF 'src/bin/entrance_client@exe/entrance_conf.c.o.d' -o 'src/bin/entrance_client@exe/entrance_conf.c.o' -c ../entrance/src/bin/entrance_conf.c
In file included from ../entrance/src/bin/entrance_conf.c:1:0:
../entrance/src/bin/entrance_client.h:5:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.
[5/26] Compiling C object 'src/bin/entrance_client@exe/entrance_login.c.o'.
FAILED: src/bin/entrance_client@exe/entrance_login.c.o 
ccache cc  -Isrc/bin/entrance_client@exe -Isrc/bin -I../entrance/src/bin -I/usr/include/elementary-1 -I/usr/include/libdrm -I/usr/include/ecore-wl2-1 -I/usr/include/ecore-fb-1 -I/usr/include/ecore-x-1 -I/usr/include/elocation-1 -I/usr/include/emotion-1 -I/usr/include/ethumb-client-1 -I/usr/include/ethumb-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/eio-1 -I/usr/include/efreet-1 -I/usr/include/ecore-ipc-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-drm2-1 -I/usr/include/elput-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/evas-1 -I/usr/include/evas-1/canvas -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/luajit-2.1 -I/usr/include/eet-1 -I/usr/include/emile-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -include config.h -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -pthread -MMD -MQ 'src/bin/entrance_client@exe/entrance_login.c.o' -MF 'src/bin/entrance_client@exe/entrance_login.c.o.d' -o 'src/bin/entrance_client@exe/entrance_login.c.o' -c ../entrance/src/bin/entrance_login.c
In file included from ../entrance/src/bin/entrance_login.c:1:0:
../entrance/src/bin/entrance_client.h:5:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.
[6/26] Compiling C object 'src/bin/entrance_client@exe/entrance_gui.c.o'.
FAILED: src/bin/entrance_client@exe/entrance_gui.c.o 
ccache cc  -Isrc/bin/entrance_client@exe -Isrc/bin -I../entrance/src/bin -I/usr/include/elementary-1 -I/usr/include/libdrm -I/usr/include/ecore-wl2-1 -I/usr/include/ecore-fb-1 -I/usr/include/ecore-x-1 -I/usr/include/elocation-1 -I/usr/include/emotion-1 -I/usr/include/ethumb-client-1 -I/usr/include/ethumb-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/eio-1 -I/usr/include/efreet-1 -I/usr/include/ecore-ipc-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-drm2-1 -I/usr/include/elput-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/evas-1 -I/usr/include/evas-1/canvas -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/luajit-2.1 -I/usr/include/eet-1 -I/usr/include/emile-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -include config.h -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -pthread -MMD -MQ 'src/bin/entrance_client@exe/entrance_gui.c.o' -MF 'src/bin/entrance_client@exe/entrance_gui.c.o.d' -o 'src/bin/entrance_client@exe/entrance_gui.c.o' -c ../entrance/src/bin/entrance_gui.c
In file included from ../entrance/src/bin/entrance_gui.c:1:0:
../entrance/src/bin/entrance_client.h:5:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.
[7/26] Compiling C object 'src/bin/entrance_client@exe/entrance_client.c.o'.
FAILED: src/bin/entrance_client@exe/entrance_client.c.o 
ccache cc  -Isrc/bin/entrance_client@exe -Isrc/bin -I../entrance/src/bin -I/usr/include/elementary-1 -I/usr/include/libdrm -I/usr/include/ecore-wl2-1 -I/usr/include/ecore-fb-1 -I/usr/include/ecore-x-1 -I/usr/include/elocation-1 -I/usr/include/emotion-1 -I/usr/include/ethumb-client-1 -I/usr/include/ethumb-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/eio-1 -I/usr/include/efreet-1 -I/usr/include/ecore-ipc-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-drm2-1 -I/usr/include/elput-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/evas-1 -I/usr/include/evas-1/canvas -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/luajit-2.1 -I/usr/include/eet-1 -I/usr/include/emile-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -include config.h -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -pthread -MMD -MQ 'src/bin/entrance_client@exe/entrance_client.c.o' -MF 'src/bin/entrance_client@exe/entrance_client.c.o.d' -o 'src/bin/entrance_client@exe/entrance_client.c.o' -c ../entrance/src/bin/entrance_client.c
In file included from ../entrance/src/bin/entrance_client.c:1:0:
../entrance/src/bin/entrance_client.h:5:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.
[8/26] Compiling C object 'src/bin/entrance_client@exe/entrance_conf_theme.c.o'.
FAILED: src/bin/entrance_client@exe/entrance_conf_theme.c.o 
ccache cc  -Isrc/bin/entrance_client@exe -Isrc/bin -I../entrance/src/bin -I/usr/include/elementary-1 -I/usr/include/libdrm -I/usr/include/ecore-wl2-1 -I/usr/include/ecore-fb-1 -I/usr/include/ecore-x-1 -I/usr/include/elocation-1 -I/usr/include/emotion-1 -I/usr/include/ethumb-client-1 -I/usr/include/ethumb-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/eio-1 -I/usr/include/efreet-1 -I/usr/include/ecore-ipc-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-drm2-1 -I/usr/include/elput-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/evas-1 -I/usr/include/evas-1/canvas -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/luajit-2.1 -I/usr/include/eet-1 -I/usr/include/emile-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -include config.h -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -pthread -MMD -MQ 'src/bin/entrance_client@exe/entrance_conf_theme.c.o' -MF 'src/bin/entrance_client@exe/entrance_conf_theme.c.o.d' -o 'src/bin/entrance_client@exe/entrance_conf_theme.c.o' -c ../entrance/src/bin/entrance_conf_theme.c
In file included from ../entrance/src/bin/entrance_conf_theme.c:1:0:
../entrance/src/bin/entrance_client.h:5:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.
[10/26] Compiling C object 'src/bin/entrance_client@exe/entrance_connect.c.o'.
FAILED: src/bin/entrance_client@exe/entrance_connect.c.o 
ccache cc  -Isrc/bin/entrance_client@exe -Isrc/bin -I../entrance/src/bin -I/usr/include/elementary-1 -I/usr/include/libdrm -I/usr/include/ecore-wl2-1 -I/usr/include/ecore-fb-1 -I/usr/include/ecore-x-1 -I/usr/include/elocation-1 -I/usr/include/emotion-1 -I/usr/include/ethumb-client-1 -I/usr/include/ethumb-1 -I/usr/include/edje-1 -I/usr/include/ecore-audio-1 -I/usr/include/eio-1 -I/usr/include/efreet-1 -I/usr/include/ecore-ipc-1 -I/usr/include/embryo-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-drm2-1 -I/usr/include/elput-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/ecore-file-1 -I/usr/include/ecore-con-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/evas-1 -I/usr/include/evas-1/canvas -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/luajit-2.1 -I/usr/include/eet-1 -I/usr/include/emile-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -include config.h -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -pthread -MMD -MQ 'src/bin/entrance_client@exe/entrance_connect.c.o' -MF 'src/bin/entrance_client@exe/entrance_connect.c.o.d' -o 'src/bin/entrance_client@exe/entrance_connect.c.o' -c ../entrance/src/bin/entrance_connect.c
In file included from ../entrance/src/bin/entrance_connect.c:2:0:
../entrance/src/bin/entrance_client.h:5:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by wltjr** [comment]
Strange as it generates the config.h file, something went wrong. You can see if the local build for use with xephyr works just so see if tails there as well.
```
./utils/local_build.sh
```
It will build it in the source directory and setup a test dir. If you want can run xephyr after
```
./utils/entrance_xephyr.sh
```

Otherwise thanks for the report. I just added meson like yesterday so its super new.

**Comment by SolarAquarion** [comment]
The local build fails

**Comment by wltjr** [comment]
Figures since the other did. I will see if I can replicate

**Comment by wltjr** [comment]
When you attempt a compile does a build/config.h file get generated? If not seems something maybe off with meson. Not sure why it would not get generated. If it is generated, then its a path issue.

**Comment by SolarAquarion** [comment]
It is generated, but it doesn't show up in the path I suppose

On Aug 23, 2017 9:43 PM, "William L Thomson Jr" <notifications@github.com>
wrote:

When you attempt a compile does a build/config.h file get generated? If not
seems something maybe off with meson. Not sure why it would not get
generated. If it is generated, then its a path issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Obsidian-StudiosInc/entrance/issues/7#issuecomment-324508781>,
or mute the thread

**Comment by wltjr** [comment]
Ok thats good know, I was not sure I included it correctly. It seems to show in the output above, but not sure on path, etc.
```
-O0 -g -include config.h -march=x86-64
```

**Comment by SolarAquarion** [comment]
Like it works with autotools, but not meson which is weird

**Comment by SolarAquarion** [comment]
It does include it in build which is weird

**Comment by wltjr** [comment]
Its because meson likes to generate it in the sources directory and I am not sure I am including that properly. Not sure why it does not fail for me, but I have some ideas to fix. autotools generates it in the root directory and makes a bit bigger mess. How I am doing it now, meson would not let me specify a path.

**Comment by SolarAquarion** [comment]
Yeah, I had to copy config.h to /usr/include for it to build!!!

**Comment by wltjr** [comment]
Seems to be a combo of how meson allows you to use that generated file, or my lack of understanding. Along with some cruft in the package I want to remove, like 
```
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
```
Stuff fails without that, so those conditionals need not exist really.

**Comment by wltjr** [comment]
Meson is very strange playing with this changes the failure in other fun ways... No error on file not being found, but errors on its contents not being found... Clearly not a quick or easy fix... Minus one for meson.

**Comment by SolarAquarion** [comment]
There is a irc channel

**Comment by wltjr** [comment]
I ended up on IRC and got a suggestion that was not documented. I saw some other issues open [[1]]( https://groups.google.com/forum/#!topic/mesonbuild/qPXHhselJjU ) [[2]](https://github.com/mesonbuild/meson/issues/1139) that I was trying. Seems its a combination of both 
```
top_inc  = include_directories('.')
add_project_arguments('-DHAVE_CONFIG_H=1', language : 'c')
```

Then passing top_inc to anything that needs config.h. Not the best but works for now. May be better in another location added to targets source directories or something.

**Comment by SolarAquarion** [comment]
it works great, thanks for the fix.

**Comment by SolarAquarion** [comment]
It seemingly doesn't install entrance.conf to /etc/entrance/entrance.conf

**Comment by wltjr** [comment]
Good to know. Does it install it anywhere? I haven't messed with install via meson yet. Can keep this one open or a new either way. I will look into it when I get a chance.

**Comment by SolarAquarion** [comment]
it's not anywhere in the build directory, which means it's not copied over

**Comment by wltjr** [comment]
Yeah another weird thing it maybe but not in that. There should be an entrance.conf in the build directory. Generated along with a entrance.service. Looking myself I just have the entrance.service, but no error for the missing entrance.conf. It does not seem to allow you to create your own subdirectories. I have to look into the install aspect.

**Comment by SolarAquarion** [comment]
I basically just did a install -dm644 for the pkgbuild

**Comment by wltjr** [comment]
Sure ways around for now, but build system should help with such.

**Comment by wltjr** [comment]
Looking into the install stuff, I will have an update at some point maybe today or tomorrow. I will reference this in the commit.

**Comment by wltjr** [comment]
That fixed fixes install but breaks build... meson is fun...

**Comment by SolarAquarion** [comment]
Installing /home/solaraquarion/pkgbuild/entrance-git/src/build/entrance.conf to /home/solaraquarion/pkgbuild/entrance-git/pkg/entrance-git/etc/pam.d
Installing /home/solaraquarion/pkgbuild/entrance-git/src/entrance/data/entrance to /home/solaraquarion/pkgbuild/entrance-git/pkg/entrance-git/etc/pam.d

**Comment by wltjr** [comment]
That was all me that time, sloppy, lazy. I copied the wrong line and deleted the one I should have kept. Corrected now sorry about that one....

**Comment by wltjr** [comment]
Build issues with meson should be resolved now. I dropped autotools and am using meson in travis, etc.
