### ISSUE TITLE
So i'm updating my arch pkgbuild

### ISSUE THREAD

**Issue by SolarAquarion** [Obsidian-StudiosInc/entrance#8]
I'm wonder if you can tag the current database as 0.1 alpha

**Comment by wltjr** [comment]
I will later today, want to get in another fix and maybe some minor stuff. I think I have most the major issues addressed so should be usable by others. At least to log in. Customization is still heavily broken...

**Comment by SolarAquarion** [comment]
I just decided to printf "0.1............."

On Sep 3, 2017 10:00 AM, "William L Thomson Jr" <notifications@github.com>
wrote:

I will later today, want to get in another fix and maybe some minor stuff.
I think I have most the major issues addressed so should be usable by
others. At least to log in. Customization is still heavily broken...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Obsidian-StudiosInc/entrance/issues/8#issuecomment-326806732>,
or mute the thread

**Comment by wltjr** [comment]
Added an initial tag.
